version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - run: npm install
      - run: npm run clean
      - run: npm run test
      - run: npm run clean

workflows:
  version: 2
  test:
    jobs:
      - test
