version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - run: npm install
      - run: npm run clean
      - run: npm run coverage
      - run: npm run codacy
      - run: npm run clean
      - store_artifacts:
          path: ./coverage

workflows:
  version: 2
  test:
    jobs:
      - test
